---
- hosts: database
  become: yes
  vars_files:
    - vars/database_vars.yml
  roles:
    - role: geerlingguy.mysql
  tasks:
  - name: disable selinux
    ansible.posix.selinux:
      state: disabled
    notify: reboot
  - name: open up port 3306
    ansible.posix.firewalld:
      service: mysql
      permanent: yes
      state: enabled

  handlers:
    - name: reboot
      reboot: