---
- hosts: web
  become: yes
  tasks:
    - name: disable selinux
      ansible.posix.selinux:
        state: disabled
      notify: reboot
    # - name: enable caddy repository
    #   shell: |
    #     dnf install 'dnf-command(copr)'
    #     dnf copr enable @caddy/caddy
    #   when: ansible_facts['os_family'] == "RedHat"
    - name: install 'dnf-command(copr)'
      dnf:
        name: 'dnf-command(copr)'
        state: latest
    - name: enable caddy repo
      shell: 
        cmd: dnf copr enable @caddy/caddy -y
    - name: install caddy
      dnf:
          name: caddy
          enablerepo: '@caddy/caddy'
          state: latest 
    - name: enable caddy
      service:
        name: caddy
        state: started
        enabled: yes
    - name: copy caddyfile
      template:
        dest: /etc/caddy/Caddyfile
        src: ../webserver/Caddyfile
      notify: reload caddy
    - name: configure User App Directory
      file:
        path: /var/www/userApp
        state: directory
    - name: configure User API Directory
      file:
        path: /var/www/userApi
        state: directory
    - name: install dotnet core sdk
      dnf:
        name: dotnet-sdk-3.1
        state: latest
    # - name: copy users-api.service file
    #   template:
    #     dest: /etc/systemd/system/users-api.service 
    #     src: ../webserver/users-api.service 
    #   notify: restart service
    # - name: start service
    #   service:
    #     name: users-api.service
    #     state: started
    #     enabled: yes

  handlers:
    - name: reload caddy
      service:
        name: caddy
        state: reloaded
    - name: reload api-user service
      service: 
        name: users-api.service
        state: restarted
    - name: reboot
      reboot: