all:
  children:
    database:
      hosts:
        dev-db:
          ansible_host: 192.168.0.41
    web:
      hosts:
        dev-web:
          ansible_host: 192.168.0.40
      vars: 
        site_address: dev.playground.alexcook.dev
        aspnetcore_environment: Development