all:
  children:
    dev:
      hosts:
        dev-web:
          ansible_host: 192.168.0.40
          # ansible_ssh_user: root
          # ansible_ssh_pass: 8astronomyc
        dev-db:
          ansible_host: 192.168.0.41
    database:
      hosts:
        dev-db:
          ansible_host: 192.168.0.41
    web:
      hosts:
        dev-web:
          ansible_host: 192.168.0.40