trigger:
  branches:
    include:
    - master
    - feature/build_pipelines
  paths:
    include:
    - api/Users/*
    exclude:
    - README.md
stages:
- stage: Build
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: build
    steps:
      - task: UseDotNet@2
        displayName: 'Install .Net Core 3.1'
        inputs:
          version: '3.1.x'

      - task: DotNetCoreCLI@2
        displayName: 'Build'
        inputs:
          command: build
          arguments: '/warnaserror'
          workingDirectory: 'api/Users'
      
      - task: DotNetCoreCLI@2
        displayName: Dotnet Publish
        inputs:
          command: publish
          publishWebProjects: True
          arguments: '--output $(Build.ArtifactStagingDirectory)'
          workingDirectory: 'api/Users'

      - task: PublishBuildArtifacts@1
        displayName: Publish Artifact
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'UsersAPI'
          publishLocation: 'Container'
- stage: Deploy
  jobs:
  - deployment: UserApi
    displayName: Deploy UserApi
    environment: Dev.dev-web
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: sudo systemctl stop users-api.service
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/UsersAPI/**/*.zip'
              destinationFolder: '/var/www/userApi'
              cleanDestinationFolder: true
          - bash: sudo systemctl start users-api.service
